%anggota_keluarga
node(buyut).
node(kakek).
node(ayah).
node(paman).
node(bibi).
node(lucas).
node(karina).
node(dino).
node(booby).
node(wendy).

%hubungan
parent(buyut,kakek).
parent(kakek,ayah).
parent(kakek,paman).
parent(kakek,bibi).
parent(ayah,lucas).
parent(ayah,karina).
parent(paman,dino).
parent(paman,booby).
parent(bibi,wendy).

%saudara_kandung
sibling(ayah,paman).
sibling(ayah,bibi).
sibling(paman,bibi).
sibling(lucas,karina).
sibling(dino,booby).

%hubungan_ponakan
uncle(paman,lucas).
uncle(paman,karina).
uncle(paman,wendy).
uncle(ayah,dino).
uncle(ayah,booby).
uncle(ayah,wendy).
aunt(bibi,lucas).
aunt(bibi,karina).
aunt(bibi,dino).
aunt(bibi,booby).

%sepupu
cousin(lucas,dino).
cousin(lucas,booby).
cousin(lucas,wendy).
cousin(karina,dino).
cousin(karina,booby).
cousin(karina,wendy).
cousin(dino,wendy).
cousin(booby,wendy).
